import { MD3DarkTheme } from 'react-native-paper';
import { AppColors } from './colors';

export const customTheme = {
  ...MD3DarkTheme,
  dark: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: AppColors.limeGreen,
    primaryContainer: AppColors.limeGreen,
    secondary: AppColors.oliveGreen,
    secondaryContainer: AppColors.oliveGreen,
    tertiary: AppColors.coral,
    tertiaryContainer: AppColors.coral,
    surface: AppColors.surface,
    surfaceVariant: AppColors.surfaceVariant,
    surfaceDisabled: '#1F1F1F',
    background: AppColors.background,
    error: AppColors.coral,
    errorContainer: '#3D1F1A',
    onPrimary: AppColors.textOnPrimary,
    onPrimaryContainer: AppColors.textOnPrimary,
    onSecondary: AppColors.textOnPrimary,
    onSecondaryContainer: AppColors.textOnPrimary,
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#FFFFFF',
    onSurface: AppColors.textPrimary,
    onSurfaceVariant: AppColors.textSecondary,
    onError: '#FFFFFF',
    onErrorContainer: AppColors.textPrimary,
    onBackground: AppColors.textPrimary,
    outline: AppColors.border,
    outlineVariant: AppColors.divider,
    inverseSurface: '#E6E6E6',
    inverseOnSurface: AppColors.almostBlack,
    inversePrimary: '#7A9E28',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.7)',
    elevation: {
      level0: 'transparent',
      level1: AppColors.surface,
      level2: '#1F1F1F',
      level3: AppColors.surfaceVariant,
      level4: '#2A2A2A',
      level5: AppColors.surfaceElevated,
    },
  },
};
